"""OpenAI-compatible request/response models"""

from typing import List, Optional, Union, Dict, Any, Literal
from pydantic import BaseModel, Field, ConfigDict


class ChatMessage(BaseModel):
    """OpenAI chat message format"""
    role: Literal["system", "user", "assistant", "tool", "function"] = Field(..., description="Role of the message author")
    content: Optional[Union[str, List[Dict[str, Any]]]] = Field(None, description="Message content")
    name: Optional[str] = Field(None, description="Optional name of the participant")
    refusal: Optional[str] = Field(None, description="Refusal message if model refuses to respond")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(None, description="Tool calls generated by the model")
    tool_call_id: Optional[str] = Field(None, description="Tool call ID for tool messages")
    
    model_config = ConfigDict(extra="allow")


class ChatCompletionRequest(BaseModel):
    """OpenAI chat completion request - fully compliant with OpenAI API spec"""
    model: str = Field(..., description="ID of the model to use")
    messages: List[Union[ChatMessage, Dict[str, Any]]] = Field(..., description="List of messages comprising the conversation")
    
    # Sampling parameters
    temperature: Optional[float] = Field(None, ge=0, le=2, description="Sampling temperature (0-2)")
    top_p: Optional[float] = Field(None, ge=0, le=1, description="Nucleus sampling parameter")
    n: Optional[int] = Field(None, ge=1, description="Number of chat completion choices to generate")
    
    # Response control
    stream: Optional[bool] = Field(None, description="Whether to stream back partial progress")
    stream_options: Optional[Dict[str, Any]] = Field(None, description="Options for streaming response")
    stop: Optional[Union[str, List[str]]] = Field(None, description="Up to 4 sequences where the API will stop generating")
    max_tokens: Optional[int] = Field(None, description="Maximum number of tokens to generate")
    max_completion_tokens: Optional[int] = Field(None, description="Upper bound for tokens in completion")
    
    # Penalties
    presence_penalty: Optional[float] = Field(None, ge=-2, le=2, description="Penalize new tokens based on presence")
    frequency_penalty: Optional[float] = Field(None, ge=-2, le=2, description="Penalize new tokens based on frequency")
    logit_bias: Optional[Dict[str, float]] = Field(None, description="Modify likelihood of specified tokens")
    
    # Response format
    response_format: Optional[Dict[str, Any]] = Field(None, description="Format of model output")
    
    # Determinism
    seed: Optional[int] = Field(None, description="Random seed for deterministic sampling")
    
    # Tools and functions
    tools: Optional[List[Dict[str, Any]]] = Field(None, description="List of tools the model may call")
    tool_choice: Optional[Union[str, Dict[str, Any]]] = Field(None, description="Controls which tool is called")
    parallel_tool_calls: Optional[bool] = Field(None, description="Whether to enable parallel function calling")
    
    # Metadata
    user: Optional[str] = Field(None, description="Unique identifier for end-user")
    metadata: Optional[Dict[str, str]] = Field(None, description="Developer-defined tags and values")
    
    # Advanced features
    logprobs: Optional[bool] = Field(None, description="Whether to return log probabilities")
    top_logprobs: Optional[int] = Field(None, ge=0, le=20, description="Number of most likely tokens to return")
    service_tier: Optional[Literal["auto", "default"]] = Field(None, description="Service tier for processing")
    
    # Audio (for models supporting audio output)
    modalities: Optional[List[str]] = Field(None, description="Output types to generate")
    audio: Optional[Dict[str, Any]] = Field(None, description="Parameters for audio output")
    
    # Predictions
    prediction: Optional[Dict[str, Any]] = Field(None, description="Static predicted output content")
    
    model_config = ConfigDict(extra="allow")


class ChatCompletionChoice(BaseModel):
    """OpenAI chat completion choice"""
    index: int = Field(..., description="Index of the choice")
    message: ChatMessage = Field(..., description="Chat completion message")
    finish_reason: Optional[Literal["stop", "length", "content_filter", "tool_calls", "function_call"]] = Field(
        None, description="Reason the model stopped generating tokens"
    )
    logprobs: Optional[Dict[str, Any]] = Field(None, description="Log probability information")


class ChatCompletionUsage(BaseModel):
    """Token usage statistics"""
    prompt_tokens: int = Field(..., description="Number of tokens in the prompt")
    completion_tokens: int = Field(..., description="Number of tokens in the completion")
    total_tokens: int = Field(..., description="Total tokens used")
    completion_tokens_details: Optional[Dict[str, Any]] = Field(None, description="Breakdown of completion tokens")
    prompt_tokens_details: Optional[Dict[str, Any]] = Field(None, description="Breakdown of prompt tokens")


class ChatCompletionResponse(BaseModel):
    """OpenAI chat completion response"""
    id: str = Field(..., description="Unique identifier for the chat completion")
    object: Literal["chat.completion"] = Field("chat.completion", description="Object type")
    created: int = Field(..., description="Unix timestamp of when the completion was created")
    model: str = Field(..., description="Model used for the chat completion")
    choices: List[ChatCompletionChoice] = Field(..., description="List of chat completion choices")
    usage: Optional[ChatCompletionUsage] = Field(None, description="Usage statistics")
    system_fingerprint: Optional[str] = Field(None, description="Backend configuration fingerprint")
    service_tier: Optional[str] = Field(None, description="Service tier used for processing")


class ChatCompletionChunk(BaseModel):
    """OpenAI streaming chunk"""
    id: str = Field(..., description="Unique identifier for the chat completion")
    object: Literal["chat.completion.chunk"] = Field("chat.completion.chunk", description="Object type")
    created: int = Field(..., description="Unix timestamp")
    model: str = Field(..., description="Model used")
    choices: List[Dict[str, Any]] = Field(..., description="List of completion choices")
    usage: Optional[ChatCompletionUsage] = Field(None, description="Usage statistics (only in final chunk if requested)")
    system_fingerprint: Optional[str] = Field(None, description="Backend configuration fingerprint")
    service_tier: Optional[str] = Field(None, description="Service tier used")


class CompletionRequest(BaseModel):
    """OpenAI completion request (legacy)"""
    model: str
    prompt: Union[str, List[str]]
    temperature: Optional[float] = Field(1.0, ge=0, le=2)
    max_tokens: Optional[int] = Field(16)
    top_p: Optional[float] = Field(1.0, ge=0, le=1)
    n: Optional[int] = Field(1)
    stream: Optional[bool] = Field(False)
    logprobs: Optional[int] = Field(None)
    echo: Optional[bool] = Field(False)
    stop: Optional[Union[str, List[str]]] = Field(None)
    presence_penalty: Optional[float] = Field(0, ge=-2, le=2)
    frequency_penalty: Optional[float] = Field(0, ge=-2, le=2)
    user: Optional[str] = Field(None)


class ModelInfo(BaseModel):
    """OpenAI model information"""
    id: str = Field(..., description="Model identifier")
    object: Literal["model"] = Field("model", description="Object type")
    created: int = Field(..., description="Unix timestamp of when the model was created")
    owned_by: str = Field(..., description="Organization that owns the model")


class ModelList(BaseModel):
    """OpenAI model list response"""
    object: Literal["list"] = Field("list", description="Object type")
    data: List[ModelInfo] = Field(..., description="List of model objects")


class ErrorResponse(BaseModel):
    """OpenAI error response"""
    error: Dict[str, Any] = Field(..., description="Error information")


class ErrorDetail(BaseModel):
    """OpenAI error detail"""
    message: str = Field(..., description="Error message")
    type: str = Field(..., description="Error type")
    param: Optional[str] = Field(None, description="Parameter that caused the error")
    code: Optional[str] = Field(None, description="Error code")
